# Generated by Django 3.1.2 on 2020-11-03 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.countries')),
            ],
            options={
                'verbose_name': 'Slider',
            },
        ),
    ]
